---
- hosts: all
  become: true
  vars:
    ros2_user:
        name: ubuntu
        group: ubuntu
    ros2_configuration: desktop
    ros2_distribution: humble

    ros2_packages:
      - rviz2
      - joy
      - joy-teleop

  roles:
    - role: incebellipipo.ros2
    - role: gantsign.visual-studio-code
      users:
        - username: ubuntu
          visual_studio_code_extensions:
            - ms-python.python
            - ms-iot.vscode-ros
            - ms-vscode-remote.vscode-remote-extensionpack
            - ms-vscode.cmake-tools
            - ms-toolsai.jupyter
            - ms-python.debugpy
  tasks:
    - name: Install pip
      ansible.builtin.apt:
        name:
          - python3-pip
          - python-is-python3
          - tmux
          - vim
          - htop
        state: present
    - name: Install python packages
      pip:
        name:
          - jupyterlab
          - numpy
          - scipy
          - matplotlib
